In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
import pandas as pd

from src.database.queries import get_customer_data
from src.preprocessing.clean_data import clean_data

In [3]:
df = get_customer_data()

df.head()

,row_number,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,is_active_member,estimated_salary,exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
clean_df = clean_data(df)

clean_df.head()

,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,is_active_member,estimated_salary,exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
clean_df.columns.tolist()

['credit_score',
 'geography',
 'gender',
 'age',
 'tenure',
 'balance',
 'num_of_products',
 'has_cr_card',
 'is_active_member',
 'estimated_salary',
 'exited']

In [6]:
from src.preprocessing.feature_engineering import feature_engineering

In [7]:
feature_df = feature_engineering(clean_df)

feature_df.head()

,credit_score,gender,age,tenure,balance,num_of_products,has_cr_card,is_active_member,estimated_salary,exited,geography_Germany,geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,1

In [8]:
feature_df.columns.tolist()

['credit_score',
 'gender',
 'age',
 'tenure',
 'balance',
 'num_of_products',
 'has_cr_card',
 'is_active_member',
 'estimated_salary',
 'exited',
 'geography_Germany',
 'geography_Spain']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = feature_df.drop("exited", axis=1)
y = feature_df["exited"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (10000, 11)
Target Shape: (10000,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [12]:
print("Training Set :", X_train.shape)
print("Testing Set  :", X_test.shape)

Training Set : (8000, 11)
Testing Set  : (2000, 11)

In [13]:
print("Original Dataset")
print(y.value_counts(normalize=True))

print("\nTraining Dataset")
print(y_train.value_counts(normalize=True))

print("\nTesting Dataset")
print(y_test.value_counts(normalize=True))

Original Dataset
exited
0    0.7963
1    0.2037
Name: proportion, dtype: float64

Training Dataset
exited
0    0.79625
1    0.20375
Name: proportion, dtype: float64

Testing Dataset
exited
0    0.7965
1    0.2035
Name: proportion, dtype: float64